name: Release KAIZEN BOT 1.0

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate package layout
        run: |
          test -d "KAIZEN BOT 1.0/Includes" \ 
            && test -f "KAIZEN BOT 1.0/ProfessionalTradingBot.mq5" \ 
            && test -f "KAIZEN BOT 1.0/Test.mq5"

      - name: Create ZIP
        run: |
          zip -r "KAIZEN BOT 1.0.zip" "KAIZEN BOT 1.0"

      - name: Upload Release Asset (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            KAIZEN BOT 1.0.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact (manual run)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: KAIZEN-BOT-1.0
          path: KAIZEN BOT 1.0.zip